# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplota as plt
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib.pyplota'

In [4]:
df = pd.read_csv("/Users/kartheekseemala/Downloads/bill_authentication.csv")
df.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [5]:
df.shape

(1372, 5)

In [7]:
df.describe().T

count      mean       std      min       25%      50%       75%  \
Variance  1372.0  0.433735  2.842763  -7.0421 -1.773000  0.49618  2.821475   
Skewness  1372.0  1.922353  5.869047 -13.7731 -1.708200  2.31965  6.814625   
Curtosis  1372.0  1.397627  4.310030  -5.2861 -1.574975  0.61663  3.179250   
Entropy   1372.0 -1.191657  2.101013  -8.5482 -2.413450 -0.58665  0.394810   
Class     1372.0  0.444606  0.497103   0.0000  0.000000  0.00000  1.000000   

              max  
Variance   6.8248  
Skewness  12.9516  
Curtosis  17.9274  
Entropy    2.4495  
Class      1.0000

In [11]:
X = df.drop('Class',axis=1)
y = df['Class']
print(X.shape)
print(y.shape)

(1372, 4)
(1372,)


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [14]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[159   1]
 [  0 115]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       160
           1       0.99      1.00      1.00       115

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [18]:
from sklearn.svm import SVC
clf = SVC(kernel='poly',degree=8)
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[93 67]
 [52 63]]
              precision    recall  f1-score   support

           0       0.64      0.58      0.61       160
           1       0.48      0.55      0.51       115

    accuracy                           0.57       275
   macro avg       0.56      0.56      0.56       275
weighted avg       0.58      0.57      0.57       275



In [22]:
from sklearn.svm import SVC
clf = SVC(kernel='rbf')
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [23]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[160   0]
 [  0 115]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160
           1       1.00      1.00      1.00       115

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [24]:
from sklearn.svm import SVC
clf = SVC(kernel='sigmoid')
clf=clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[93 67]
 [52 63]]
              precision    recall  f1-score   support

           0       0.64      0.58      0.61       160
           1       0.48      0.55      0.51       115

    accuracy                           0.57       275
   macro avg       0.56      0.56      0.56       275
weighted avg       0.58      0.57      0.57       275

